---
title: "Discussion"

output: html_document
---

#Discussion: 
There are more job positions located at prosperous places and downtown. It makes sense that companies and departments always located in downtown.  
We found that for base salary of jobs required for at least master degree, engineering has the highest median base salary, for base salary of jobs required for baccalaureate degree, technology has the highest median base salary, and for base salary without requirement of degree, the median base salary and the overall base salary of Engineering are all pretty high compared with other job categories.   
From 2013 to 2017, the number of job positions in each category keeps increasing. And in 2017 all categories have a dramatically increase in job positions. This might because there are more positions needed in government during recent year.  Engineering positions has greatest increasing between 2016 to 2017,and job in health has great increasing between 2015 to 2016. We may predict that there will be great needed for talents in health and engineering area. While jobs in maintance has decrease between 2013 to 2014. Maybe this is because of the development of technology, fewer manpower is needed in maintance.  
"Experience" is the top popular word in both preferred skills and requirements. It is important for people who want a job to get prepared. We may do some internship or related project to make us more competitive. Other top words in preferred skills are "written","project" and "team" . Employers always preferred candidates with strong skills especially written skills and team work.In requirements, "school" appears frequently. We may infer that education background is also important.  
Also, there exsists a linear regression between base salary and civil sevice title level, higher salary could be gained with higher level started.


#Suggestion
 