---
title: "Find a proper job in NYC -- Job analysis of NYC"
---
---
title: "Find a proper job in NYC -- Job analysis of NYC"
author: "P8105 Group 13"
date: "December 4, 2017"
output: 
  html_document:
    code_folding: hide
---
#Member:
Huilin Zhou (hz2507)  
Zhuo Li (zl2637)  
Qing Xu (qx2178)  
Zhaoyu Liu (zl2638)  

The github link is:https://github.com/xuqingsally/p8105-final-project

#Motivation: 
Many of us will find a job in recent years. In New York City government area, what type of jobs can be payed for higher salary? If that's the ideal job for me , what skills should I have before applying for it?  Also where should I rent an apartment if I want to live close to that type of positions? By looking at the NYC jobs data set from 2013 to 2017,we wish to give some advice on job catrgories, required skills and salary range for people who are seeking for a job.  


#Initial questions:
We are trying to analyze the NYC government jobs based on the salary, the requirement of the degree, locations, job type and also required skills to provide people with a viewable results to let them find the potential suitable job.  
We did the research on the question like where to find a suitable job with the highest salary. What's the highest base salary job in need of specific education degree?  
  
While doing the analysis of the dataset and making the visualization plots, we started to think about making the wordcount to analyze the preferred skills in different job category to better find out the potential suitable job for different people. Besides, we made the bar chart to find out the number of positions for each job category in each year from 2013 to 2017, and we found out the  number of job positions in each category keeps increasing, which give us better evidence to research on the question of finding suitable jobs.  
  
After analysizing job information among the data set,we will consider linearity regression model to test the association between base salary and the level of the position in the analysis. Also we want to know whether these conclusions can be generalized to other cities.  
  
#Data: 
Source: https://data.cityofnewyork.us/City-Government/NYC-Jobs/kpav-sd4t/data  
Scrape:We downloaded the data set from the website and the original data set contains 3174 job information. We selected data with information about work location, job category, preferred skills and full/part time. We want to use Google Map to get longtitute and latitute from work locations. Since the Google map has a limit of 2500 observation one time, we selected first 2500 observations from the data set.  
Cleaning:  
1. Merge job category if they are the same kind but just have different names. Finally we got 12 kinds of job categories.    
2. Unify salary unit to "Annual" and recalculated the salary range and average salary.   
3. Use Google Map to change location to longitute and latitute.  
4. Since Google map has limitation, we wrote a new data set after cleaning it and use it in the after analysize.    
  
 
#Additional analysis:
Linear regression analysis  

#Discussion: 
There are more job positions located at prosperous places and downtown. It makes sense that companies and departments always located in downtown.  
We found that for base salary of jobs required for at least master degree, engineering has the highest median base salary, for base salary of jobs required for baccalaureate degree, technology has the highest median base salary, and for base salary without requirement of degree, the median base salary and the overall base salary of Engineering are all pretty high compared with other job categories.   
From 2013 to 2017, the number of job positions in each category keeps increasing. And in 2017 all categories have a dramatically increase in job positions. This might because there are more positions needed in government during recent year.  Engineering positions has greatest increasing between 2016 to 2017,and job in health has great increasing between 2015 to 2016. We may predict that there will be great needed for talents in health and engineering area. While jobs in maintance has decrease between 2013 to 2014. Maybe this is because of the development of technology, fewer manpower is needed in maintance.  
"Experience" is the top popular word in both preferred skills and requirements. It is important for people who want a job to get prepared. We may do some internship or related project to make us more competitive. Other top words in preferred skills are "written","project" and "team" . Employers always preferred candidates with strong skills especially written skills and team work.In requirements, "school" appears frequently. We may infer that education background is also important.  
Also, there exsists a linear regression between base salary and civil sevice title level, higher salary could be gained with higher level started.



 